/* THE UNDERSTANDING EXAM — how people really ask for changes to a trip plan, and what Money Brain must take from it.
   Each case: [what they typed, what it must find, (optional) what it must NOT find].
   Codes: pace:relaxed|packed · food:vegetarian|vegan|jain vegetarian|halal · like:<category> · dislike:<category>
          fixed@HH:MM (a fixed appointment at that time) · day:N / date:N (which day it is about) · free:morning|afternoon|evening|day
          dayStart:HH:MM · dayStart:later|earlier · dayEnd:HH:MM · walking:less · kids · none (nothing to act on)
   Run: node test/exam/run.js understand */
module.exports = [
  // ---- pace: slower
  ['Day 2 is too packed', ['pace:relaxed', 'day:2']],
  ['day two feels too hectic', ['pace:relaxed', 'day:2']],
  ['too much running around on the third day', ['pace:relaxed', 'day:3']],
  ['can we slow down a bit?', ['pace:relaxed']],
  ['this is exhausting, fewer places please', ['pace:relaxed']],
  ['we want a more relaxed trip', ['pace:relaxed']],
  ['less rushed please', ['pace:relaxed']],
  ['too many things in one day', ['pace:relaxed']],
  ['cut down the sightseeing, we are tired', ['pace:relaxed']],
  ['keep it light', ['pace:relaxed']],
  ['make it easy going', ['pace:relaxed']],
  ['not so many stops a day', ['pace:relaxed']],
  ['thoda relax plan karo', ['pace:relaxed']],
  ['bahut zyada ho gaya, kam karo', ['pace:relaxed']],
  ['the last day is overloaded', ['pace:relaxed', 'day:-1']],
  ['first day too busy, we will be jet lagged', ['pace:relaxed', 'day:1']],
  // ---- pace: more
  ['day 3 looks empty, add more', ['pace:packed', 'day:3']],
  ['we want to see as much as possible', ['pace:packed']],
  ['pack more in', ['pace:packed']],
  ['too little to do', ['pace:packed']],
  ['add more places', ['pace:packed']],
  ['we are energetic, make it busier', ['pace:packed']],
  ['more sightseeing please', ['pace:packed']],
  // ---- food
  ['we are vegetarian', ['food:vegetarian']],
  ['we are veg', ['food:vegetarian']],
  ['pure veg food only', ['food:vegetarian']],
  ['no meat please', ['food:vegetarian']],
  ["we don't eat non-veg", ['food:vegetarian']],
  ['vegetarian restaurants only', ['food:vegetarian']],
  ['my wife is vegetarian', ['food:vegetarian']],
  ['veg khana chahiye', ['food:vegetarian']],
  ['we are vegan', ['food:vegan']],
  ['jain food please', ['food:jain vegetarian']],
  ['no onion no garlic, jain', ['food:jain vegetarian']],
  ['halal food only', ['food:halal']],
  ['non-veg is fine', [], ['food:vegetarian']],
  // ---- kinds of places: dislike
  ['no temples', ['dislike:temple']],
  ['skip the temples', ['dislike:temple']],
  ['no mosques please', ['dislike:mosque']],
  ['avoid malls', ['dislike:mall']],
  ['we hate shopping malls', ['dislike:mall']],
  ['no more museums', ['dislike:museum']],
  ['too many museums', ['dislike:museum']],
  ['enough museums already', ['dislike:museum']],
  ['skip the religious places', ['dislike:temple', 'dislike:mosque', 'dislike:church']],
  ['not interested in churches', ['dislike:church']],
  ["don't want to go to markets", ['dislike:market']],
  ['no souks', ['dislike:market']],
  ['remove the zoo', ['dislike:animals']],
  ['no beaches this time', ['dislike:beach']],
  ['we are not into forts', ['dislike:fort']],
  ['mandir nahi jaana', ['dislike:temple']],
  ['no theme parks', ['dislike:fun']],
  ['skip the desert safari', ['dislike:desert']],
  ['no boat rides, my mother gets seasick', ['dislike:boat']],
  ['less shopping', ['dislike:mall', 'dislike:market']],
  // ---- kinds of places: like
  ['more museums', ['like:museum']],
  ['I love museums and souks', ['like:museum', 'like:market']],
  ['we like markets', ['like:market']],
  ['add a beach day', ['like:beach']],
  ['more food places', ['like:food']],
  ['we are foodies', ['like:food']],
  ['street food please', ['like:food']],
  ['we want to try local food', ['like:food']],
  ['kids love animals, add a zoo', ['like:animals', 'kids']],
  ['add some shopping', ['like:mall', 'like:market']],
  ['a shopping day please', ['like:mall', 'like:market']],
  ['we enjoy parks and gardens', ['like:park']],
  ['more nature', ['like:park']],
  ['we like history', ['like:museum', 'like:fort']],
  ['interested in history and forts', ['like:fort']],
  ['we want great views', ['like:view']],
  ['want to see the city from above', ['like:view']],
  ['add a desert safari', ['like:desert']],
  ['a boat ride would be nice', ['like:boat']],
  ['include a theme park for the kids', ['like:fun', 'kids']],
  ['temples are a must for my parents', ['like:temple']],
  ['more art galleries', ['like:museum']],
  ['nightlife', []],
  // ---- mixed
  ['no temples, more food places', ['dislike:temple', 'like:food']],
  ['no mosques please, we are vegetarian, day 2 is too packed', ['dislike:mosque', 'food:vegetarian', 'pace:relaxed', 'day:2']],
  ['less museums more beaches', ['dislike:museum', 'like:beach']],
  ['skip malls but add markets', ['dislike:mall', 'like:market'], ['like:mall', 'dislike:market']],
  ['we love markets but hate malls', ['like:market', 'dislike:mall'], ['like:mall', 'dislike:market']],
  ['fewer museums, more time at the beach', ['dislike:museum', 'like:beach']],
  ['relaxed pace and vegetarian food', ['pace:relaxed', 'food:vegetarian']],
  // ---- fixed appointments
  ['I have a meeting on the 14th at 3 pm', ['fixed@15:00', 'date:14']],
  ['meeting on day 2 at 11am', ['fixed@11:00', 'day:2']],
  ['work call on the 24th at 4:30 pm', ['fixed@16:30', 'date:24']],
  ['dinner with friends on day 3 at 8pm', ['fixed@20:00', 'day:3']],
  ['lunch with my cousin on the 25th at 1 pm', ['fixed@13:00', 'date:25']],
  ['a wedding on day 4 at 7 pm', ['fixed@19:00', 'day:4']],
  ['we have tickets for a show on the 26th at 9 pm', ['fixed@21:00', 'date:26']],
  ['doctor appointment on day 1 at 10:15 am', ['fixed@10:15', 'day:1']],
  ['conference on 24 Dec at 9am', ['fixed@09:00', 'date:24']],
  ['cricket match on the last day at 2 pm', ['fixed@14:00', 'day:-1']],
  ['visiting my uncle on day 3 at 5pm', ['fixed@17:00', 'day:3']],
  // ---- free time
  ['keep the evening free on day 3', ['free:evening', 'day:3']],
  ['evening free on day 2', ['free:evening', 'day:2']],
  ['nothing planned on the morning of day 4', ['free:morning', 'day:4']],
  ['we want a free day', ['free:day']],
  ['keep day 5 free', ['free:day', 'day:5']],
  ['rest in the afternoon on day 2', ['free:afternoon', 'day:2']],
  ['afternoon off on the 25th', ['free:afternoon', 'date:25']],
  ['no plans on the first morning', ['free:morning', 'day:1']],
  // ---- times of day
  ['start the day at 10', ['dayStart:10:00']],
  ['start at 10:30 am', ['dayStart:10:30']],
  ['we want to start later', ['dayStart:later']],
  ['late mornings please', ['dayStart:later']],
  ['we like to sleep in', ['dayStart:later']],
  ['early starts are fine, begin at 8', ['dayStart:08:00']],
  ['start earlier', ['dayStart:earlier']],
  ['back at the hotel by 9 pm', ['dayEnd:21:00']],
  ['we need to be back by 8', ['dayEnd:20:00']],
  ['finish the day by 7pm', ['dayEnd:19:00']],
  ['no late nights', ['dayEnd:earlier']],
  // ---- people and walking
  ['my parents are with us, less walking please', ['walking:less']],
  ['grandma is in a wheelchair', ['walking:less']],
  ['we have a toddler', ['kids']],
  ['travelling with two kids aged 5 and 8', ['kids']],
  ['my father cannot walk much', ['walking:less']],
  ['less walking', ['walking:less']],
  ['too much walking on day 2', ['walking:less', 'day:2']],
  ['senior citizens with us', ['walking:less']],
  // ---- nothing to act on (must not invent actions)
  ['hello there', []],
  ['thanks, looks good', []],
  ['great plan!', []],
  ['what is the weather like?', []],
  ['ok', []],
  ['perfect', []],
];
