/* A THIRD set, written after the vocabulary work and run once: the current honest measure. */
module.exports = [
  ['we are old, go slow', ['pace:relaxed']],
  ['the schedule on the fourth day is crazy', ['pace:relaxed', 'day:4']],
  ['can we do less each day?', ['pace:relaxed']],
  ['give us more free time', ['pace:relaxed']],
  ['we can handle a busy schedule', ['pace:packed']],
  ['cram in as many sights as possible', ['pace:packed']],
  ['strictly vegetarian meals', ['food:vegetarian']],
  ['no chicken or fish for us', ['food:vegetarian']],
  ['vegan please, no dairy', ['food:vegan']],
  ['we would rather not visit temples', ['dislike:temple']],
  ['my kids hate museums', ['dislike:museum', 'kids']],
  ['please drop the souk visit', ['dislike:market']],
  ['beaches are not our thing', ['dislike:beach']],
  ['we adore markets', ['like:market']],
  ['i am a big fan of museums', ['like:museum']],
  ['please add a zoo visit', ['like:animals']],
  ['my daughter wants the beach', ['like:beach']],
  ['plan some parks for a morning walk', ['like:park']],
  ['we want to go up a tall tower', ['like:view']],
  ['shopping is a must for my wife', ['like:mall', 'like:market']],
  ['avoid churches and temples', ['dislike:church', 'dislike:temple']],
  ['more souks, less museums', ['like:market', 'dislike:museum']],
  ['zoom call on day 2 at 9 am', ['fixed@09:00', 'day:2']],
  ['an interview on the 24th at 11:30 am', ['fixed@11:30', 'date:24']],
  ['birthday dinner on day 4 at 8 pm', ['fixed@20:00', 'day:4']],
  ['keep the third evening open', ['free:evening', 'day:3']],
  ['nothing on day 2 morning please', ['free:morning', 'day:2']],
  ['start around 9:30', ['dayStart:09:30']],
  ['we are late risers', ['dayStart:later']],
  ['be back by 9', ['dayEnd:21:00']],
  ['my mom has a bad knee', ['walking:less']],
  ['a baby is with us', ['kids']],
  ['sounds good', []],
  ['brilliant, cheers', []],
  ['how much will this cost', []],
  ['is it safe there', []],
];
