/* HELD-OUT understanding exam: phrasings Money Brain was NOT tuned on — the honest measure of how well it
   generalises. Same codes as understand.exam.js. Run: node test/exam/run.js holdout */
module.exports = [
  ['the second day has way too much going on', ['pace:relaxed', 'day:2']],
  ['can you make day 4 lighter', ['pace:relaxed', 'day:4']],
  ['we are travelling with kids so a slower pace', ['pace:relaxed', 'kids']],
  ['honestly it is too ambitious', ['pace:relaxed']],
  ["we don't want to rush", ['pace:relaxed']],
  ['chill trip please', ['pace:relaxed']],
  ['aaram se plan karo', ['pace:relaxed']],
  ['we have lots of energy, fit more in', ['pace:packed']],
  ['day 3 is boring, add something', ['pace:packed', 'day:3']],
  ['my husband only eats vegetarian', ['food:vegetarian']],
  ['everyone is veg except me', ['food:vegetarian']],
  ['prefer vegetarian places to eat', ['food:vegetarian']],
  ['we eat everything', [], ['food:vegetarian']],
  ['please no mosque visits', ['dislike:mosque']],
  ['temple visits are not needed', ['dislike:temple']],
  ['we are not museum people', ['dislike:museum']],
  ['skip the markets and souks', ['dislike:market']],
  ['cancel the mall', ['dislike:mall']],
  ['i get bored in museums', ['dislike:museum']],
  ['no aquarium', ['dislike:animals']],
  ['the kids want to see dolphins', ['like:animals', 'kids']],
  ['we would love a desert trip', ['like:desert']],
  ['put in a beach afternoon', ['like:beach']],
  ['we love old forts and palaces', ['like:fort']],
  ['can we visit a gurudwara', ['like:temple']],
  ['my mother wants to visit a temple', ['like:temple']],
  ['add a cruise on the creek', ['like:boat']],
  ['something with a view at sunset', ['like:view']],
  ['more local markets, fewer malls', ['like:market', 'dislike:mall']],
  ['more beaches but no water parks', ['like:beach', 'dislike:fun']],
  ['I want to eat the best local food', ['like:food']],
  ['maximum food, minimum museums', ['like:food', 'dislike:museum']],
  ['I have a call at 6 pm on day 2', ['fixed@18:00', 'day:2']],
  ['board meeting on the 26th at 10 am', ['fixed@10:00', 'date:26']],
  ['meeting a client on day 3 at 2:30 pm', ['fixed@14:30', 'day:3']],
  ['we are going to a concert on the 27th at 8:30 pm', ['fixed@20:30', 'date:27']],
  ['dinner with the team on the second day at 7:30 pm', ['fixed@19:30', 'day:2']],
  ['keep the last evening free', ['free:evening', 'day:-1']],
  ['no plans after lunch on day 2', ['free:afternoon', 'day:2']],
  ['leave the morning of the 25th free', ['free:morning', 'date:25']],
  ['i need one full rest day', ['free:day']],
  ['we would like to start at 11', ['dayStart:11:00']],
  ["let's not start before 10 am", ['dayStart:10:00']],
  ['no early mornings please', ['dayStart:later']],
  ['back to the hotel by 10 pm', ['dayEnd:22:00']],
  ['we want to be in the hotel by 8 pm', ['dayEnd:20:00']],
  ['my grandfather uses a walker', ['walking:less']],
  ['we have a 3 year old', ['kids']],
  ['my knees hurt, minimise walking', ['walking:less']],
  ['limit walking', ['walking:less']],
  ['looks fine', []],
  ['ok thanks', []],
  ['can you share the plan', []],
  ['nice', []],
  ['how far is the airport', []],
  ['what should we wear', []],
  ['send it to my wife', []],
  ['this is great, thank you', []],
  ['love it', []],
  ['who made this plan?', []],
];
